[General]

Background=/usr/share/sddm/themes/simple-sddm/wallpaper.png

# Cor usada como fallback enquanto a imagem carrega
BackgroundColor=#111111

# Aparência
TextColor=#ffffff
SecondaryTextColor=#c8c8c8
PanelColor=#151515
FieldColor=#222222
AccentColor=#ffffff

# Data/hora
TimeFormat=HH:mm
DateFormat=dddd, d 'de' MMMM 'de' yyyy

# Se true, o último usuário é preenchido automaticamente
ForceLastUser=true
